/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from "react";
import { useFrame } from "react-three-fiber";
import { useGLTF } from "@react-three/drei/useGLTF";
import { proxy, useProxy } from "valtio";
import { setBodyParts } from "../../actions/Actions";

const state = proxy({
  current: null,
  selectedParts: [],
  items: {
    Head: "#ffffff",
    Jaw: "#ffffff", //1
    Neck: "#ffffff", //2
    Ribs: "#ffffff", //3
    Loin: "#ffffff", //4
    Hip: "#ffffff", //5
    Traps: "#ffffff", //7
    Chest: "#ffffff", //9
    Clavicle: "#ffffff", //10
    Sides: "#ffffff", //11
    Throat: "#ffffff", //58
    BackWings: "#ffffff", //61
    Abs1: "#ffffff", //62
    Abs2: "#ffffff", //63
    Abs3: "#ffffff", //65
    Shoulders: "#ffffff", //8
    Biceps: "#ffffff", //14
    Elbows: "#ffffff", //16
    Triceps: "#ffffff", //59
    Showels: "#ffffff", //60
    ForearmDown: "#ffffff", //66
    Forearm: "#ffffff", //68
    Hand: "#ffffff", //15
    Knee: "#ffffff", //17
    Calves: "#ffffff", //18
    ButtCheecks: "#ffffff", //19
    Feet: "#ffffff", //20
    LegBicepsOuter: "#ffffff", //56
    LegBicepsInner: "#ffffff", //56
    CalvesFront: "#ffffff", //57
    Middle1: "#ffffff", //40
    Middle2: "#ffffff", //40
    Middle3: "#ffffff", //40
    Pointer1: "#ffffff", //40
    Pointer2: "#ffffff", //40
    Pointer3: "#ffffff", //40
    Ring1: "#ffffff", //40
    Ring2: "#ffffff", //40
    Ring3: "#ffffff", //40
    Small1: "#ffffff", //40
    Small2: "#ffffff", //40
    Small3: "#ffffff", //40
    Thumb1: "#ffffff", //40
    Thumb2: "#ffffff", //40
    Thumb3: "#ffffff", //40
    ThumbFooter: "#ffffff", //40
  },
});

export default function Body(props) {
  const group = useRef();
  const snap = useProxy(state);
  const [hovered, set] = useState(null);
  const { nodes, materials } = useGLTF("/BodyCompressed.glb");

  // Animate model
  useFrame((state) => {
    const t = state.clock.getElapsedTime();
    group.current.position.y = (1 + Math.sin(t / 1.5)) / 10;
  });

  

  return (
    <group ref={group} {...props} dispose={null}>
      <group
        position={[0, -2.7, 0]}
        scale={[3.5, 3.5, 3.5]}
        onPointerOver={(e) => {
          e.stopPropagation();
          set(e.object.name);
        }}
        onPointerOut={(e) => {
          e.intersections.length === 0 && set(null);
        }}
        onPointerDown={(e) => {
          e.stopPropagation();
          state.current = e.object.name;
          state.items[state.current] = state.items[state.current] === "#FF0000" ? "#FFFFFF" : "#FF0000" ;

          if(state.selectedParts.includes(state.current))
            state.selectedParts = state.selectedParts.filter(e=> e !== state.current)
          else
            state.selectedParts.push(state.current)

            props.dispatch(setBodyParts(state.selectedParts));
        }}
        onPointerMissed={(e) => (state.current = null)}
      >
        {" "}
        <mesh
          name="Head"
          material-color={snap.items.Head}
          material={materials.Head}
          geometry={nodes.Head.geometry}
          position={[0, 1.64, 0.03]}
          scale={[0.12, 0.12, 0.12]}
        />
        <mesh
          name="Jaw"
          material-color={snap.items.Jaw}
          material={materials.Jaw}
          geometry={nodes.Jaw.geometry}
          position={[0, 1.5, 0]}
          scale={[0.09, 0.09, 0.09]}
        />
        <mesh
          name="Neck"
          material-color={snap.items.Neck}
          material={materials.Neck}
          geometry={nodes.Neck.geometry}
          position={[0, 1.51, 0]}
        />
        <mesh
          name="Ribs"
          material-color={snap.items.Ribs}
          material={materials.Ribs}
          geometry={nodes.Ribs.geometry}
          position={[0, -0.26, 0]}
        />
        <mesh
          name="Loin"
          material-color={snap.items.Loin}
          material={materials.Loin}
          geometry={nodes.Loin.geometry}
          position={[0, -0.26, 0]}
        />
        <mesh
          name="Hip"
          material-color={snap.items.Hip}
          material={materials.Hip}
          geometry={nodes.Hip.geometry}
          position={[0, 0.86, 0]}
          scale={[0.18, 0.18, 0.18]}
        />
        <mesh
          name="Traps"
          material-color={snap.items.Traps}
          material={materials.Traps}
          geometry={nodes.Traps.geometry}
          position={[0, -0.26, 0]}
        />
        <mesh
          name="Chest"
          material-color={snap.items.Chest}
          material={materials.Chest}
          geometry={nodes.Chest.geometry}
          position={[0, -0.26, 0]}
        />
        <mesh
          name="Clavicle"
          material-color={snap.items.Clavicle}
          material={materials.Clavicle}
          geometry={nodes.Clavicle.geometry}
          position={[0, -0.26, 0]}
        />
        <mesh
          name="Sides"
          material-color={snap.items.Sides}
          material={materials.Sides}
          geometry={nodes.Sides.geometry}
          position={[0, -0.26, 0]}
        />
        <mesh
          name="Throat"
          material-color={snap.items.Throat}
          material={materials.Throat}
          geometry={nodes.Throat.geometry}
          position={[0, 1.51, 0]}
        />
        <mesh
          name="BackWings"
          material-color={snap.items.BackWings}
          material={materials.BackWings}
          geometry={nodes.BackWings.geometry}
          position={[0, -0.26, 0]}
        />
        <mesh
          name="Abs1"
          material-color={snap.items.Abs1}
          material={materials.Abs1}
          geometry={nodes.Abs1.geometry}
          position={[0, -0.26, 0]}
        />
        <mesh
          name="Abs3"
          material-color={snap.items.Abs3}
          material={materials.Abs3}
          geometry={nodes.Abs3.geometry}
          position={[0, -0.26, 0]}
        />
        <mesh
          name="Abs2"
          material-color={snap.items.Abs2}
          material={materials.Abs2}
          geometry={nodes.Abs2.geometry}
          position={[0, -0.26, 0]}
        />
        <mesh
          name="Shoulders"
          material-color={snap.items.Shoulders}
          material={materials.Shoulders}
          geometry={nodes.Shoulders.geometry}
          position={[0, -0.26, 0]}
        />
        <mesh
          name="Biceps"
          material-color={snap.items.Biceps}
          material={materials.Biceps}
          geometry={nodes.Biceps.geometry}
          position={[0, -0.26, 0]}
        />
        <mesh
          name="Elbows"
          material-color={snap.items.Elbows}
          material={materials.Elbows}
          geometry={nodes.Elbows.geometry}
          position={[0, -0.26, 0]}
        />
        <mesh
          name="Tripceps"
          material-color={snap.items.Tripceps}
          material={materials.Tripceps}
          geometry={nodes.Triceps.geometry}
          position={[0, -0.26, 0]}
        />
        <mesh
          name="Showels"
          material-color={snap.items.Showels}
          material={materials.Showels}
          geometry={nodes.Showels.geometry}
          position={[0, -0.26, 0]}
        />
        <mesh
          name="ForearmDown"
          material-color={snap.items.ForearmDown}
          material={materials.ForearmDown}
          geometry={nodes.ForearmDown.geometry}
          position={[0, -0.26, 0]}
        />
        <mesh
          name="Forearm"
          material-color={snap.items.Forearm}
          material={materials.Forearm}
          geometry={nodes.Forearm.geometry}
          position={[0, -0.26, 0]}
        />
        <mesh
          name="Hand"
          material-color={snap.items.Hand}
          material={materials.Hand}
          geometry={nodes.Hand.geometry}
          position={[0.61, 1.04, 0.04]}
          rotation={[-1.8, 1.08, -1.5]}
          scale={[0.19, 0.19, 0.19]}
        >
          <mesh
            name="Middle1"
            material={materials.Middle1}
            material-color={snap.items.Middle1}
            geometry={nodes.Middle1.geometry}
            position={[0.05, 0.32, 0.02]}
            rotation={[-0.2, -0.07, 0]}
            scale={[0.14, 0.15, 0.14]}
          >
            <mesh
              name="Middle2"
              material={materials.Middle2}
              material-color={snap.items.Middle2}
              geometry={nodes.Middle2.geometry}
              position={[0, 0.94, -0.05]}
              rotation={[-0.25, 0, 0]}
            >
              <mesh
                name="Middle3"
                material={materials.Middle3}
                material-color={snap.items.Middle3}
                geometry={nodes.Middle3.geometry}
                position={[0, 0.79, 0]}
              />
            </mesh>
          </mesh>
          <mesh
            name="Pointer1"
            material={materials.Pointer1}
            material-color={snap.items.Pointer1}
            geometry={nodes.Pointer1.geometry}
            position={[0.2, 0.31, 0.03]}
            rotation={[-0.04, 0, -0.08]}
            scale={[0.14, 0.14, 0.14]}
          >
            <mesh
              name="Pointer2"
              material={materials.Pointer2}
              material-color={snap.items.Pointer2}
              geometry={nodes.Pointer2.geometry}
              position={[0, 0.95, -0.03]}
              rotation={[-0.14, 0, 0]}
            >
              <mesh
                name="Pointer3"
                material={materials.Pointer3}
                material-color={snap.items.Pointer3}
                geometry={nodes.Pointer3.geometry}
                position={[0, 0.79, 0]}
              />
            </mesh>
          </mesh>
          <mesh
            name="Ring1"
            material={materials.Ring1}
            material-color={snap.items.Ring1}
            geometry={nodes.Ring1.geometry}
            position={[-0.1, 0.29, 0]}
            rotation={[-0.18, -0.28, 0.13]}
            scale={[0.14, 0.13, 0.14]}
          >
            <mesh
              name="Ring2"
              material={materials.Ring2}
              material-color={snap.items.Ring2}
              geometry={nodes.Ring2.geometry}
              position={[0, 0.9, -0.08]}
              rotation={[-0.49, 0, 0]}
            >
              <mesh
                name="Ring3"
                material={materials.Ring3}
                material-color={snap.items.Ring3}
                geometry={nodes.Ring3.geometry}
                position={[0, 0.79, 0]}
              />
            </mesh>
          </mesh>
          <mesh
            name="Small1"
            material={materials.Small1}
            material-color={snap.items.Small1}
            geometry={nodes.Small1.geometry}
            position={[-0.22, 0.21, -0.03]}
            rotation={[-0.19, -0.59, 0.26]}
            scale={[0.12, 0.11, 0.12]}
          >
            <mesh
              name="Small2"
              material={materials.Small2}
              material-color={snap.items.Small2}
              geometry={nodes.Small2.geometry}
              position={[0, 0.92, -0.07]}
              rotation={[-0.52, 0, 0]}
            >
              <mesh
                name="Small3"
                material={materials.Small3}
                material-color={snap.items.Small3}
                geometry={nodes.Small3.geometry}
                position={[0, 0.79, -0.01]}
                rotation={[-0.28, 0, 0]}
              />
            </mesh>
          </mesh>
          <mesh
            name="Thumb1"
            material={materials.Thumb1}
            material-color={snap.items.Thumb1}
            geometry={nodes.Thumb1.geometry}
            position={[0.27, -0.1, -0.02]}
          />
          <mesh
            name="Thumb2"
            material={materials.Thumb2}
            material-color={snap.items.Thumb2}
            geometry={nodes.Thumb2.geometry}
            position={[0.3, 0.06, -0.17]}
            rotation={[1.01, 1.47, -1.16]}
            scale={[0.16, 0.16, 0.16]}
          >
            <mesh
              name="Thumb3"
              material={materials.Thumb3}
              material-color={snap.items.Thumb3}
              geometry={nodes.Thumb3.geometry}
              position={[0, 0.79, 0]}
            />
          </mesh>
          <mesh
            name="ThumbFooter"
            material={materials.ThumbFooter}
            material-color={snap.items.ThumbFooter}
            geometry={nodes.ThumbFooter.geometry}
            position={[0.27, -0.1, -0.02]}
          />
        </mesh>
        <mesh
          name="Calves"
          material-color={snap.items.Calves}
          material={materials.Calves}
          geometry={nodes.Calves.geometry}
          position={[0, -0.28, 0]}
        />
        <mesh
          name="ButtCheeks"
          material-color={snap.items.ButtCheeks}
          material={materials.ButtCheeks}
          geometry={nodes.ButtCheecks.geometry}
          position={[0, -0.26, 0]}
        />
        <mesh
          name="Feet"
          material-color={snap.items.Feet}
          material={materials.Feet}
          geometry={nodes.Feet.geometry}
          position={[0, -0.28, 0]}
        />
        <mesh
          name="LegBicepsOuter"
          material-color={snap.items.LegBicepsOuter}
          material={materials.LegBicepsOuter}
          geometry={nodes.LegBicepsOuter.geometry}
          position={[0, -0.28, 0]}
        />
        <mesh
          name="CalvesFront"
          material-color={snap.items.CalvesFront}
          material={materials.CalvesFront}
          geometry={nodes.CalvesFront.geometry}
          position={[0, -0.28, 0]}
        />
        <mesh
          name="LegBicepsInner"
          material-color={snap.items.LegBicepsInner}
          material={materials.LegBicepsInner}
          geometry={nodes.LegBicepsInner.geometry}
          position={[0, -0.28, 0]}
        />
        <mesh
          name="Knee"
          material-color={snap.items.Knee}
          material={materials.Knee}
          geometry={nodes.Knee.geometry}
          position={[0, -0.28, 0]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/BodyCompressed.glb");






